This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./tudkom.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file tudkom.acn....done (98 entries accepted, 0 rejected).
Sorting entries....done (767 comparisons).
Generating output file tudkom.acr....done (37 lines written, 0 warnings).
Output written in tudkom.acr.
Transcript written in tudkom.alg.
